version: 2
project_name: d4s

before:
  hooks:
    - go mod tidy

builds:
  - id: d4s
    main: ./cmd/d4s
    binary: d4s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

    ldflags:
      - -s -w
      - -X github.com/jr-k/d4s/internal/buildinfo.Version={{.Version}}
      - -X github.com/jr-k/d4s/internal/buildinfo.Commit={{.Commit}}
      - -X github.com/jr-k/d4s/internal/buildinfo.Date={{.Date}}

dockers_v2:
  - id: d4s
    images:
      - "ghcr.io/jr-k/d4s"
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
    dockerfile: Dockerfile.release
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch \"386\" }}x86{{ else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE*
      - README*
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: jr-k
    name: d4s

brews:
  - name: d4s
    repository:
      owner: jr-k
      name: homebrew-d4s
    directory: Formula
    homepage: "https://d4scli.io"
    description: "Master Docker like a pro, right from your terminal"
    license: "Apache-2.0"
    install: |
      bin.install "d4s"

nfpms:
  - id: d4s
    package_name: d4s
    maintainer: "jr-k <jrk@jierka.com>"
    description: "Master Docker like a pro, right from your terminal"
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk
      - ipk
      - archlinux
    contents:
      - src: LICENSE
        dst: /usr/share/doc/d4s/LICENSE
      - src: README.md
        dst: /usr/share/doc/d4s/README.md
    bindir: /usr/bin

scoops:
  - name: d4s
    repository:
      owner: jr-k
      name: scoop-d4s
    homepage: https://d4scli.io
    description: "Master Docker like a pro, right from your terminal"
    license: Apache-2.0
    commit_author:
      name: GoReleaser Bot
      email: bot@goreleaser.com
